version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: intern-hub-minio
    ports:
      - "9000:9000" # Cổng API (Spring Boot của bro sẽ gọi vào cổng này)
      - "9001:9001" # Cổng Giao diện Web (Bro dùng trình duyệt vào cổng này)
    environment:
      MINIO_ROOT_USER: minioadmin # Đóng vai trò là AWS Access Key
      MINIO_ROOT_PASSWORD: minioadmin # Đóng vai trò là AWS Secret Key
    command: server /data --console-address ":9001"
    volumes:
      - minio_local_data:/data # Mount volume để tắt Docker đi ảnh không bị mất

volumes:
  minio_local_data: